name: Printing Echo

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: node-ng
    env:
      Greeting: Hello
    steps:
      - name: "ONE"
        run: |
          echo "Welcome to 1st echo"
          echo "Repo Name: ${{ github.repository }}"
          echo "WORKSPACE: ${{ github.workspace }}"
          echo " Waint for 10 sec"
          timeout /t 10
          
      - name: "TWO"
        run: |
          echo "Welcome to the 2nd Run 1st echo"
          echo "Welcome to the 2nd Run 2nd echo"
          
