name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "ONE"
        run: |
          echo "Welcome to 1st echo"
          echo "Welcome to the 2nd echo"
      - name: "TWO"
        run: |
          echo "Welcome to the 2nd Run 1st echo"
          echo "Welcome to the 2nd Run 2nd echo"
          
