name: Printing Echo

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: node-ng
    env:
      Greeting: Hello
    steps:
      - name: "ONE"
        run: |
          working-directory: ${{env.GITHUB_WORKSPACE}}
          echo "Welcome to 1st echo"
          echo "Repo Name: ${{ github.repository }}"
          echo "WORKSPACE: ${{env.GITHUB_WORKSPACE}}"
          
      - name: "TWO"
        run: |
          echo "Welcome to the 2nd Run 1st echo"
          echo "Welcome to the 2nd Run 2nd echo"
          
